builds:
  - id: linux-amd64
    main: ./
    binary: helm-ls
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X main.Version={{ .Env.VERSION }} -X main.GitCommit={{ .Env.GIT_COMMIT }} -X main.CompiledBy={{ .Env.COMPILED_BY }}  -X main.Branch={{ .Env.BRANCH_NAME }} -X main.BuildTime={{ .Env.BUILD_TIME }}
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
